/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javac.ecj.problems;

import com.sun.tools.javac.api.JavacTaskImpl;

import javax.tools.DocumentationTool;
import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;
import java.util.List;
import java.io.File;

public class App {

    private static String javacTestFile = "TypeMismatch.java";
    private static String javadocTestFile = "Javadoc.java";

    public static void main(String[] args) {
        //javadoc();
        javac();
        //testAmbiguous();
    }

    private static void javadoc() {
        DocumentationTool documentationTool = ToolProvider.getSystemDocumentationTool();
        var compUnits = documentationTool.getStandardFileManager(null, null, null).getJavaFileObjects(new File("app\\src\\testFiles\\" + javadocTestFile));
        DocumentationTool.DocumentationTask task = documentationTool.getTask(null, null, new JavacDiagnosticsListener(), null, null, compUnits);
        task.call();
    }

    private static void javac() {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        List<String> options = List.of("--release=" + 11, "-Xlint:all"); //$NON-NLS-1$
        var compUnits = compiler.getStandardFileManager(new JavacDiagnosticsListener(), null, null).getJavaFileObjects(new File("app\\src\\testFiles\\" + javacTestFile));
        JavacTaskImpl task = (JavacTaskImpl) compiler.getTask(null, null, new JavacDiagnosticsListener(), options, null, compUnits);
        task.call();
    }

    private static void testAmbiguous() {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        List<String> options = List.of("--release=" + 11, "-Xlint:all"); //$NON-NLS-1$
        var compUnits = compiler.getStandardFileManager(new JavacDiagnosticsListener(), null, null).getJavaFileObjects(new File(".\\app\\src\\testFiles\\" + "Ambiguous.java"), new File(".\\app\\src\\testFiles\\pkg1\\" + "A.java"), new File(".\\app\\src\\testFiles\\pkg2\\" + "A.java"));
        JavacTaskImpl task = (JavacTaskImpl) compiler.getTask(null, null, new JavacDiagnosticsListener(), options, null, compUnits);
        task.call();
    }

}
